# Exported from Render on 2026-02-02T13:59:43Z
version: "1"
databases:
- name: fusionauth
  databaseName: fusionauth_db
  plan: free
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "18"

services:
- type: web
  name: fusionauth-app:latest
  runtime: image
  image:
    url: docker.io/fusionauth/fusionauth-app:latest
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: POSTGRES_PASSWORD
    sync: false
  - key: POSTGRES_USER
    sync: false
  - key: FUSIONAUTH_APP_RUNTIME_MODE
    value: development
  - key: DATABASE_USERNAME
    sync: false
