# Exported from Render on 2026-02-02T13:59:43Z
version: "1"
projects:
- name: FusionAuth Project
  environments:
  - name: Production
    services:
    - type: web
      name: fusionauth-app:latest
      runtime: image
      image:
        url: docker.io/fusionauth/fusionauth-app:latest
      plan: free
      envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fusionauth_db
          property: connectionString
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: fusionauth_db
          property: password
      - key: POSTGRES_USER
        fromDatabase:
          name: fusionauth_db
          property: user
      - key: FUSIONAUTH_APP_RUNTIME_MODE
        value: development
      - key: DATABASE_USERNAME
        sync: false
    databases:
    - name: fusionauth
      databaseName: fusionauth_db
      user: bryanrobinson
      plan: free
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
